USE 50_DAYS_SQL_CHALLENGES;

CREATE TABLE DEPARTMENTS
(DEPT_ID VARCHAR(40),
DEPT_NAME VARCHAR(40));

CREATE TABLE EMPLOYEES
(
    EMP_ID VARCHAR(40),
    EMP_NAME VARCHAR(40),
    AGE VARCHAR(40),
    CITY VARCHAR(40),
    DEPT_ID VARCHAR(40),
    HIRE_DATE VARCHAR(40)
);

CREATE TABLE SALARIES
(
    SALARY_ID VARCHAR(40),
    EMP_ID VARCHAR(40),
    SALARY VARCHAR(40),
    SALARY_DATE VARCHAR(40)
);

CREATE TABLE ATTENDANCE
(
    ATTENDANCE_ID VARCHAR(40),
    EMP_ID VARCHAR(40),
    ATTENDANCE_DATE VARCHAR(40),
    STATUS VARCHAR(40)
);

CREATE TABLE PERFORMANCE
(
    EMP_ID VARCHAR(40),
    RATING_2022 VARCHAR(40),
    RATING_2023 VARCHAR(40),
    RATING_2024 VARCHAR(40)
);
